### ISSUE TITLE
The 2(3)-class classification on each dataset.

### ISSUE THREAD

**Issue by Rem1L** [HornHehhf/SocREval#2]
Could you please opensource your result of 2-class and 3-class classification of each of the 4 dataset in your paper?

**Comment by HornHehhf** [comment]
Sorry for my late response. The detailed results of 2-class and 3-class classification (as well as 5-class classification) for each dataset are as follows:

GPT-4 on GSM8K
5-class: [0.57, 0.67, 0.68, 0.63, 0.64, 1.46, 0.78, 0.64, 0.32]
3-class: [0.56, 0.64, 0.66, 0.62, 0.72, 0.68, 0.34, 0.72, 0.63]
2-class: [0.63, 0.66, 0.66, 0.66, 0.82, 0.42, 0.18, 0.82, 0.81]

SocREval on GSM8K
5-class: [0.81, 0.91, 0.89, 0.8, 0.7, 0.73, 0.36, 0.7, 0.41]
3-class: [0.79, 0.8, 0.87, 0.8, 0.77, 0.48, 0.23, 0.77, 0.69]
2-class: [0.9, 0.9, 0.9, 0.9, 0.95, 0.22, 0.05, 0.95, 0.95]

GPT-4 on e-SNLI
5-class: [0.24, 0.45, 0.41, 0.37, 0.48, 1.16, 0.77, 0.48, 0.22]
3-class: [0.21, 0.3, 0.29, 0.29, 0.52, 0.69, 0.48, 0.52, 0.31]
2-class: [0.2, 0.28, 0.28, 0.28, 0.57, 0.66, 0.43, 0.57, 0.53]

SocREval on e-SNLI
5-class: [0.58, 0.65, 0.62, 0.56, 0.56, 0.97, 0.6, 0.56, 0.46]
3-class: [0.55, 0.55, 0.55, 0.54, 0.73, 0.52, 0.27, 0.73, 0.58]
2-class: [0.52, 0.53, 0.53, 0.53, 0.77, 0.48, 0.23, 0.77, 0.76]

GPT-4 on DROP
5-class: [0.42, 0.64, 0.64, 0.57, 0.49, 1.33, 0.87, 0.49, 0.29]
3-class: [0.42, 0.56, 0.55, 0.52, 0.52, 0.73, 0.5, 0.52, 0.45]
2-class: [0.38, 0.43, 0.43, 0.43, 0.64, 0.6, 0.36, 0.64, 0.63]

SocREval on DROP
5-class: [0.49, 0.7, 0.63, 0.55, 0.46, 1.12, 0.74, 0.46, 0.33]
3-class: [0.44, 0.51, 0.5, 0.47, 0.57, 0.68, 0.44, 0.57, 0.5]
2-class: [0.4, 0.4, 0.4, 0.4, 0.68, 0.57, 0.32, 0.68, 0.68]

GPT-4 on Cosmos QA
5-class: [0.39, 0.46, 0.46, 0.38, 0.3, 1.65, 1.2, 0.3, 0.28]
3-class: [0.27, 0.3, 0.3, 0.28, 0.47, 0.86, 0.6, 0.47, 0.44]
2-class: [0.28, 0.22, 0.22, 0.22, 0.73, 0.52, 0.27, 0.73, 0.6]

SocREval on Cosmos QA
5-class: [0.42, 0.49, 0.49, 0.41, 0.38, 1.46, 1.01, 0.38, 0.35]
3-class: [0.32, 0.37, 0.38, 0.36, 0.57, 0.72, 0.46, 0.57, 0.5]
2-class: [0.22, 0.24, 0.24, 0.24, 0.82, 0.42, 0.18, 0.82, 0.62]

Note that the numbers in each list indicate the results under the measures as in Tables 9-10: Somers’ D (SD), metrics encompass Pearson’s Correlation Coefficient (r), Spearman’s Rank Correlation Coefficient (ρ), Kendall’s τ (τ ), Accuracy (ACC), Root Mean Squared Error (RMSE), Mean Absolute Error (MAE), Micro F1 Score (Micro-F1), and Macro F1 Score (Macro-F1).

Feel free to let me know if you have any questions.

Best,
Hangfeng

**Comment by Rem1L** [comment]
Thanks for your reply. I want to know about how is the ACC measured? Is it based on ANY_ERROR or overall quality.

**Comment by HornHehhf** [comment]
It's based on the overall quality.
